fail_fast: true
repos:
- repo: local
  hooks:
  - id: winipedia-utils
    name: winipedia-utils
    entry: python -m winipedia_utils.git.pre_commit.run_hooks
    language: system
    always_run: true
    pass_filenames: false

  - id: build
    name: build
    entry: python -m video_vault.build_project.build
    language: system
    always_run: true
    pass_filenames: false
