# Generated by Django 5.2.4 on 2025-07-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_position',
            field=models.BigIntegerField(default=0),
        ),
    ]
